# Generated by Django 4.0.2 on 2022-04-05 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_alter_classname_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='student',
            field=models.ManyToManyField(related_name='stu', to=settings.AUTH_USER_MODEL),
        ),
    ]
