# Generated by Django 4.0.2 on 2022-04-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_classname_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='codeTime',
            field=models.IntegerField(null=True),
        ),
    ]
