# Generated by Django 4.0.2 on 2022-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='motive',
            field=models.CharField(default=1, max_length=54),
        ),
    ]
