# Generated by Django 4.0.2 on 2022-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feePaid',
            field=models.BooleanField(default=1),
        ),
    ]
