# Generated by Django 4.0.2 on 2022-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_user_feepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feePaid',
            field=models.BooleanField(default=False),
        ),
    ]
